//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockEditorTest {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockEditorTest.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Blockly XML (*.blockly;*.xml)|*.blockly;*.xml|JavaScript (*.js)|*.js|All Files (*.*)|*.* 的當地語系化字串。
        /// </summary>
        internal static string f_filetypes {
            get {
                return ResourceManager.GetString("f_filetypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///Program Ends.
        /// 的當地語系化字串。
        /// </summary>
        internal static string f_run_ends {
            get {
                return ResourceManager.GetString("f_run_ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///Error at line {1}: {0} 的當地語系化字串。
        /// </summary>
        internal static string f_run_error {
            get {
                return ResourceManager.GetString("f_run_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test Running 的當地語系化字串。
        /// </summary>
        internal static string f_testform_title {
            get {
                return ResourceManager.GetString("f_testform_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;File 的當地語系化字串。
        /// </summary>
        internal static string m_file {
            get {
                return ResourceManager.GetString("m_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Exit 的當地語系化字串。
        /// </summary>
        internal static string m_file_exit {
            get {
                return ResourceManager.GetString("m_file_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Import... 的當地語系化字串。
        /// </summary>
        internal static string m_file_import {
            get {
                return ResourceManager.GetString("m_file_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;New 的當地語系化字串。
        /// </summary>
        internal static string m_file_new {
            get {
                return ResourceManager.GetString("m_file_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Open... 的當地語系化字串。
        /// </summary>
        internal static string m_file_open {
            get {
                return ResourceManager.GetString("m_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Save 的當地語系化字串。
        /// </summary>
        internal static string m_file_save {
            get {
                return ResourceManager.GetString("m_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save &amp;As... 的當地語系化字串。
        /// </summary>
        internal static string m_file_saveas {
            get {
                return ResourceManager.GetString("m_file_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Test 的當地語系化字串。
        /// </summary>
        internal static string m_test {
            get {
                return ResourceManager.GetString("m_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Run... 的當地語系化字串。
        /// </summary>
        internal static string m_test_run {
            get {
                return ResourceManager.GetString("m_test_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Turbo Mode 的當地語系化字串。
        /// </summary>
        internal static string m_test_turbo {
            get {
                return ResourceManager.GetString("m_test_turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 res/js/lang/en.js 的當地語系化字串。
        /// </summary>
        internal static string script_path {
            get {
                return ResourceManager.GetString("script_path", resourceCulture);
            }
        }
    }
}
